deployment:
  name: my-simple-app
  labels:
    app: my-simple-app # Should be same as service.metadata.labels.app
  spec:
    template:
      spec:
        containers:
          - registry: "docker.io/kebonce40/"
            image_name: "golang-simple-app"
            name: "my-simple-app"
            tag: ":latest"
          - registry: "docker.io/kebonce40/"
            image_name: "golang-simple-app"
            name: "prometheus-sidecar"
            tag: ":printHeaderPromLatest"

service:
  metadata:
    name: my-simple-app-svc
    labels:
      app: my-simple-app  # Should be same as deployment.labels.app
  spec:
    type: NodePort
    ports:
      - name: msa-port
        nodeport: 30808
        port: 8080
      - name: msa-prom-port
        nodeport: 30911
        port: 9110