deployment:
  name: my-simple-app
  labels:
    app: my-simple-app # Should be same as service.metadata.labels.app
  spec:
    template:
      spec:
        containers:
          registry: "kebonce40/"
          image_name: "golang-simple-app"
          tag: ":latest"

service:
  metadata:
    name: my-simple-app-svc
    labels:
      app: my-simple-app  # Should be same as deployment.labels.app
  spec:
    type: NodePort
    ports:
      port:
        value: 8080