deployment:
  name: my-simple-app
  labels:
    app: my-simple-app
  spec:
    template:
      spec:
        containers:
          registry: "kebonce40/"
          image_name: "golang-simple-app"
          tag: ":latest"

service:
  metadata:
    name: my-simple-app
    labels:
      app: my-simple-app-svc
  spec:
    type: NodePort
    ports:
      port:
        value: 8080