apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment.labels.app }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
      - image: {{ .Values.deployment.spec.template.spec.containers.registry}}{{ .Values.deployment.spec.template.spec.containers.image_name}}{{ .Values.deployment.spec.template.spec.containers.tag}}
        name: {{ .Values.deployment.spec.template.spec.containers.image_name}}
        resources: {}
status: {}