apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment.labels.app }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
      - image: {{ .Values.deployment.spec.template.spec.containers.registry[0]}}{{ .Values.deployment.spec.template.spec.containers.image_name[0]}}{{ .Values.deployment.spec.template.spec.containers.tag[0]}}
        name: {{ .Values.deployment.spec.template.spec.containers.image_name[0]}}
        resources: {}
      - image: {{ .Values.deployment.spec.template.spec.containers.registry[1]}}{{ .Values.deployment.spec.template.spec.containers.image_name[1]}}{{ .Values.deployment.spec.template.spec.containers.tag[1]}}
        name: {{ .Values.deployment.spec.template.spec.containers.image_name[1]}}
        resources: {}
status: {}