apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.deployment.labels.app }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
      {{- range .Values.deployment.spec.template.spec.containers}}
      - image: {{ .registry}}{{ .image_name}}{{ .tag}}
        name: {{ .image_name}}
        resources: {}
      {{- end }}
status: {}