apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port.value }}
    protocol: TCP
    targetPort: {{ .Values.service.port.value }}
  selector:
    app: {{ .Values.service.name }}
status:
  loadBalancer: {}