apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.service.metadata.labels.app }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.service.metadata.name }}
spec:
  ports:
  {{- range .Values.service.spec.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  {{- end }}
  selector:
    app: {{ .Values.service.metadata.labels.app }}
  type: {{ .Values.service.spec.type }}
status:
  loadBalancer: {}