apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.service.metadata.labels.app }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.service.metadata.name }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
  - port: {{ .Values.service.spec.ports.port.value }}
    protocol: TCP
    targetPort: {{ .Values.service.spec.ports.port.value }}
  selector:
    app: {{ .Values.service.metadata.labels.app }}
status:
  loadBalancer: {}